### ISSUE TITLE
Add a repo with AragonOS, AragonID abis

### ISSUE THREAD

**Issue by 0xGabi** [aragon/contract-helpers#4]
Currently the aragonCLI and the wrapper are using `@aragon/os` only to import the abis from this one. This is not efficient at all and we could improve that having a package that include the abis

**Comment by 0xGabi** [comment]
After talking it with @sohkai, he suggested me to instead we might want to have an aditional distribution for the ABIs on the aragonOS repo

**Comment by sohkai** [comment]
It may also be the case that `@aragon/os` only installs a lot of packages because it exposes its truffle config as a `dependency` (and not a `devDependency`, as it should be).

I think if we moved the truffle and etc. configuration out of `@aragon/os`, installing that package would be much faster :).
